import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const roboto = Roboto({
  weight: ["400","500", "700","900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} px-`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
